ContactManager [STEP 2] Jason, Blue
tasty-code/ios-cantact-manager pull request #13
Opened 2022-12-29 02:45 UTC by bomyuniverse

안녕하세요, @zdodev !! Jason & Blue입니다! 😄
사전에 양해 부탁드렸던 내용처럼 STEP 2 구현까지는 코드에 큰 변화가 없어 STEP 3 까지 진행 후 PR 요청드립니다!
첫 프로젝트라 그런지 아쉬운 부분들이 많았지만 그래도 열심히 작성하였습니다!!
이전 STEP 1 PR 시 정상적으로 작동하지 않았던 부분들을 개선하였습니다! 😆
벌써 2022년의 마지막 주도 절반이나 지나버렸네요 🥲
리뷰 잘 부탁드리겠습니다! 연말이라 많이 바쁘실 텐데 시간내어 리뷰해 주셔서 감사합니다! 🙇🏻🙇🏻

## 🧑🏼‍💻 작업 목록

[ STEP 2 ]
- [x]  사용자에게 동작을 선택할 메뉴를 표기합니다.
- [x]  1, 2, 3, x 외의 입력을 받으면 잘못된 입력을 알리고 다시 메뉴를 출력합니다.
- [x]  연락처 추가와 종료 기능만 우선 구현합니다.

[ STEP 3 ]
- [x]  연락처 목록 보기 기능을 구현합니다.
    - [x]  목록은 이름순으로 출력합니다.
- [x]  연락처 검색 기능을 구현합니다.
    - [x]  검색 결과의 출력 순서는 입력받았던 순서와 무관합니다.

### 💡상세 요구사항 분석

- [x]  연락처 목록 및 검색 결과 출력 시 출력 형식 →  `- 이름 / 나이 / 전화번호`

## 💭 학습 키워드

- 정규표현식(RegularExpression)
- guard (Early Exit)
- optional
- split, map, filter
- Set

## 🤔 고민과 해결

### Blue

1. STEP 1에서 고민했던 구분자 `/`를 기준으로 구분하는 방법을 변경하였습니다.
    - 기존에는 구분자가 위치하는 index number를 이용하는 방식이었지만, index out of range가 발생할 위험이 있다고 판단하여
    구분자의 index number를 활용하여 단어를 join 하는 것보다 안전한 방법을 선택하였습니다.
    - [String](https://developer.apple.com/documentation/swift/string/) 문서의 Splitting a string 부분을 읽고 **`split`** 메서드를 활용해 보았습니다.
2. split 메서드를 사용한 후 반환된 타입이 [String.Subsequence] 타입이라서 [String] 타입을 매개변수로 받는 함수의 파라미터로 전달할 때
문제가 발생하였습니다.
    - Jason의 도움으로 고차함수 [map(_:)](https://developer.apple.com/documentation/swift/array/map(_:)-87c4d)에 대해 이해해보는 시간을 가져보고, 이를 타입 변환에 사용하여 보았습니다.

## 🙋🏻 질문 거리

### Blue

1. 입력받은 문자열을 처리하는 과정이 복잡하여 다른 팀의 해결방법도 설명을 들어보곤 하였습니다.
올바른 사용자 입력 형태 케이스가 2가지라서 각각 다른 방법을 사용하고 있었습니다.
    - 저희의 방법은 아래와 같습니다.
        
        ```swift
        // ContactManager.swift
        
        let convertedUserInputValues = convertor.convertToCharacter(this: receiveUserInputValues)
        let removedBlankUserInputValues = detector.excludeSpaceWord(convertedUserInputValues)
        let combinedUserInputValues = convertor.convertToString(removedBlankUserInputValues)
        let splitedUserInputValues = combinedUserInputValues.split(separator: "/").map{ String($0) }
        ```
        
        1. 사용자로부터 입력받은 String을 [Character]로 변경
        3. [Character] 중 공백문자 **`“ “`** 제거
        4. 공백문자가 제거된 배열을 String 으로 변환
        5. split 메서드를 사용하여 [String] 으로 변환
    - 다른 팀의 방법은 아래와 같습니다.
        
        ```swift
        let splitInput = input.components(separatedBy: "/").map {
                    $0.replacingOccurrences(of: " ", with: "")
        ```
        
        1. 사용자로부터 입력받은 String에 split 메서드를 사용하여 [String] 으로 변환
        2. 1의 과정에 map 메서드를 사용하여 [String] 내부에 있는 값들을 하나씩 꺼낸 후replacingOccurrences() 메서드를 사용하여
        공백 문자`” “`를 빈 문자`””`로 대체
    - 다른팀의 방법을 듣고 해당 방법을 참고하려고 하였으나 공백문자를 빈 문자로 대체하는 과정이 3번 정도 반복되는 일이라고 생각되어,
    입력받은 문자에서 공백을 우선적으로 제거하는 것이 효율적이라고 판단하였습니다!
    - 저희의 방법도 틀린 방법은 아닌 것 같지만 조금 더 효율적인 방법이 있다면 학습하여 나중에 활용해 보고자 합니다!
    혹시 소대의 의견은 어떤가요?

2022-12-30 05:38 UTC, zdodev requested changes
안녕하세요! Jason & Blue!

step 2 기능구현 정말 잘해주셨습니다!😄

남겨주신 질문에 대한 제 생각은 Jason & Blue 팀의 문자열 처리도 틀린 방법이 아닙니다!
공백 처리에 대한 순서와 처리할 때 사용한 로직이 다를 뿐이라고 생각합니다!
다만, 다른 팀이 작성한 것 처럼 고차함수를 활용한 방식이 가독성이 좋다고 생각하여 더 선호하는 편입니다!
이와 관련하여 고차함수에 대해 학습해보면 더 좋을 것 같습니다!😁

몇 가지 궁금한 사항을 남겨보았습니다.
확인 부탁드립니다!🤗

2022-12-30 05:38 UTC, zdodev commented on ContactManager/ContactManager/Model/Checker.swift
> +        target.indices.forEach{
다른 클로저처럼 `{` 앞에 공백을 삽입하면 좋을 것 같습니다!

2022-12-30 05:38 UTC, zdodev commented on ContactManager/ContactManager/Model/Checker.swift
> +            switch $0 {
용도가 명확하지 않는 이상 클로저의 인자명을 생략하는 것은 가독성이 떨어질 수 있을 것 같습니다.
`$0` 대신 이름을 지어줘보는 것은 어떨까요? 의견이 궁금합니다!

2022-12-30 05:38 UTC, zdodev commented on ContactManager/ContactManager/Model/Checker.swift
> +            case 0:
case 0, 1, 2 각 케이스 내 구문이 형태가 비슷하여 메서드로 추출할 수 있을 것 같습니다.
중복되는 코드를 메서드로 분리해볼 수 있을까요?

2022-12-30 05:38 UTC, zdodev commented on ContactManager/ContactManager/Model/Checker.swift
> +                    nameValue = target[0]          // 값 지정
불필요한 주석일 경우 제거하는 것이 더 좋을 것 같습니다!

2022-12-30 05:38 UTC, zdodev commented on ContactManager/ContactManager/Model/Checker.swift
> +        guard nameValue != "" && ageValue != "" && phoneNumberValue != "" else {
`!= ""` 대신 `nameValue.isEmpty` 와 같은 프로퍼티를 사용하는 것은 어떨까요?

2022-12-30 05:38 UTC, zdodev commented on ContactManager/ContactManager/Model/ContactManager.swift
>  final class ContactManager {
`final` 키워드를 사용한 클래스와 사용하지 않은 클래스의 기준이 궁금합니다!

2022-12-30 05:38 UTC, zdodev commented on ContactManager/ContactManager/Model/ContactManager.swift
> +    var contactInformationArray: Set<ContactInformation> = []
타입은 `Set` 이지만 이름을 보면 실제 `Array` 타입과 헷갈릴 수 있을 것 같습니다.
`Array` 대신 다른 이름을 사용해보는 것은 어떨까요?

2022-12-30 05:38 UTC, zdodev commented on ContactManager/ContactManager/Model/ContactManager.swift
> +                break
매 case 마다 `break` 를 작성하신 이유가 궁금합니다!

2022-12-30 05:38 UTC, zdodev commented on ContactManager/ContactManager/Model/ContactManager.swift
> +                exit(1)
프로그램을 강제 종료하는 구문보다는 동작을 다 수행하고 나서 로직에 따라 종료되도록 구현하는 것은 어떨까요?

2022-12-30 05:38 UTC, zdodev commented on ContactManager/ContactManager/Model/ContactManager.swift
> +        } while identifier == true
다음도 좋아보입니다!
```swift
} while identifier
```

2022-12-30 05:38 UTC, zdodev commented on ContactManager/ContactManager/Model/ContactManager.swift
> +    enum MenuStart: String, CustomStringConvertible {
`MenuList` 이름은 어떤가요? 의견이 궁금합니다!

2022-12-30 05:38 UTC, zdodev commented on ContactManager/ContactManager/Model/ContactManager.swift
> +        if receiveUserInputValues == "" {
`== ""` 대신 `receiveUserInputValues.isEmpty` 와 같은 프로퍼티를 사용하는 것은 어떨까요?

2022-12-30 05:38 UTC, zdodev commented on ContactManager/ContactManager/Model/ContactManager.swift
> +        let splitedUserInputValues = combinedUserInputValues.split(separator: "/").map{ String($0) }
`map` 과 `{` 를 붙여서 작성하신 이유가 있을까요?

2022-12-30 05:38 UTC, zdodev commented on ContactManager/ContactManager/Storage/PrintMessage.swift
> +    case choiceWrorngMenu = "선택이 잘못되었습니다 확인 후 다시 입력해주세요.\n"
오타가 있는 것 같습니다!

2022-12-30 05:38 UTC, zdodev commented on ContactManager/ContactManager/Storage/PrintMessage.swift
> +    static func viewContact(list: Set<ContactInformation>) {
`printContact` 이름은 어떤지 궁금합니다!

2022-12-30 05:38 UTC, zdodev commented on ContactManager/ContactManager/Storage/PrintMessage.swift
> +        }
고차함수를 사용해보셨네요.👍

2022-12-30 05:38 UTC, zdodev commented on ContactManager/ContactManager/Storage/PrintMessage.swift
> +        let confirmContactArray = list.filter{$0.name == word}
`filter` 와 `{` 를 붙여서 작성하신 이유가 있을까요?

2022-12-30 05:38 UTC, zdodev commented on ContactManager/ContactManager/Storage/RegularExpression.swift
>  enum RegularExpression: String, CustomStringConvertible {
정규표현식 좋습니다!👍

2022-12-30 06:52 UTC, JasonLee0223 commented on ContactManager/ContactManager/Model/Checker.swift
> +        target.indices.forEach{
앗.. 공백 실수가 있었네요..😅 수정하여 반영하겠습니다!

2022-12-30 06:59 UTC, JasonLee0223 commented on ContactManager/ContactManager/Model/Checker.swift
> +            switch $0 {
target의 타입이 [String] 이여서 각 배열의 요소를 사용해보려고 하였는데 forEach가 익숙하지 않아 index값으로 진행하는게 방향으로 정하게 되었습니다...! 하여 switch의 `$0`와 index의 Int type이 비슷한 느낌이 들어 사용하였습니다.
소대의 말처럼 후행클로저가 가독성이 떨어져서 더 읽기 좋게 바꾸어 보려고 노력하는중인데 한 번 더 집어주셔서 감사합니다!

2022-12-30 06:59 UTC, bomyuniverse commented on ContactManager/ContactManager/Model/Checker.swift
> +        var phoneNumberValue: String = ""
Jason의 경우 타입을 생략하는 코딩 스타일을 가지고 있고, 저는 타입을 명시하는 코딩 스타일을 가지고 있습니다.
못 보고 지나쳤던 부분인데, 다시 보니 해당 부분에 대해서 팀 컨벤션을 정하고 작업했다면 더 좋았을 거 같네요! 😓 
타입 명시, 생략의 경우 현업에서는 어떻게 더 많이 사용하는지 궁금합니다!

2022-12-30 07:01 UTC, bomyuniverse commented on ContactManager/ContactManager/Model/Checker.swift
> +                    nameValue = target[0]          // 값 지정
앗... 급하게 작성하다보니 실수가 있었네요! 불필요한 주석 삭제하여 반영하도록 하겠습니다! 감사합니다! 😢

2022-12-30 07:04 UTC, JasonLee0223 commented on ContactManager/ContactManager/Model/Checker.swift
> +            case 0:
넵! 메서드로 분리할 수 있을 것 같습니다! 시도해보고 적용해보겠습니다!

2022-12-30 07:07 UTC, JasonLee0223 commented on ContactManager/ContactManager/Model/ContactManager.swift
> +    var contactInformationArray: Set<ContactInformation> = []
앗... 그렇네요.. 저와 블루 모두 Set을 사용해본 경험이 적어 당시 Custom Type에 Hashable 채택하는데 학습을 진행하다가 빼먹은 것 같습니다..ㅠㅠ 다음에는 좀 더 꼼꼼히 보도록 노력하겠습니다!

2022-12-30 07:07 UTC, bomyuniverse commented on ContactManager/ContactManager/Model/Checker.swift
> +        guard nameValue != "" && ageValue != "" && phoneNumberValue != "" else {
`.isEmpty` 프로퍼티 사용을 시도하였다가 실패하여서 위와 같은 코드로 작성하였습니다.
다시 코드 히스토리를 보니 기존에 `nameValue`, `ageValue`, `phoneNumberValue` 를 Bool Type으로 선언하였는데 이를 수정하는 과정에서 Bool Type에 `.isEmpty` 프로퍼티를 사용했던 것 같습니다!
해당 부분 프로퍼티 사용하여 조금 더 깔끔한 코드로 작성해 보겠습니다! 감사합니다! 💙

2022-12-30 07:12 UTC, bomyuniverse commented on ContactManager/ContactManager/Model/ContactManager.swift
>  final class ContactManager {
`final` 키워드를 사용하는 경우 다른 클래스에 상속되지 않는 클래스가 된다고 이해하였습니다.
현재 저희 코드에서 상속이 이루어지고 있는 부분이 없어서 다른 클래스와의 차이는 없으나, ContactManager가 프로그램의 시작, 종료를 관리하는 최상위 클래스라는 점에서, 코드를 볼 때 최상위 코드를 빠르게 식별할 수 있기 위해 사용하였습니다.
또한, 클래스와 구조체의 사용처를 구분하는 것이 아직 미숙하여 조금 더 익숙한 클래스를 사용하였습니다. 해당 부분은 프로젝트 종료 후 개별적으로 학습하여 다음 프로젝트 시에는 명확하게 이유를 구분하고 사용할 수 있도록 노력하겠습니다! 감사합니다! 🙏 💙

2022-12-30 07:13 UTC, JasonLee0223 commented on ContactManager/ContactManager/Model/ContactManager.swift
> +                break
이 부분은 저의 습관같이 들어간 부분입니다..😅
Caller가 호출한 뒤 잘못된 값이 입력되어 돌아왔을때 break point를 걸어서 확인하는 것을 좀 좋아하다보니 사용하게되었습니다 ^^;;

2022-12-30 07:20 UTC, JasonLee0223 commented on ContactManager/ContactManager/Model/ContactManager.swift
> +                exit(1)
맞습니다! fatalError() 또는 exit() 처럼 강제로 종료하는 구문은 지양하는것으로 알고있습니다!
생각을 해보면 항상 제 코드에 대한 자신감이 조금 부족해서 썼다고 생각이 되어집니다..😂

2022-12-30 07:22 UTC, bomyuniverse commented on ContactManager/ContactManager/Storage/PrintMessage.swift
> +        let confirmContactArray = list.filter{$0.name == word}
클로저의 경우 공백을 넣어주는 것이 맞다고 이해하였으나, 고차함수를 처음 사용해보아서 실수가 있었네요...!
고차함수의 클로저도 다른 일반 함수의 클로저 처럼 띄어서 작성하는 것을 방금 알게 되었습니다! 주의하겠습니다! 👍

2022-12-30 07:26 UTC, bomyuniverse commented on ContactManager/ContactManager/Model/ContactManager.swift
> +        } while identifier == true
해당 값이 바뀌어야 종료되는 반복문이라 true 일 때 반복한다는 것을 명시해 주는 게 좋을 것이라 판단하여 `== true`를 사용해 주었습니다!
혹시 `while identifier`로 개선해주신 이유가 있을까요!? 설명해 주시면 감사하겠습니다! 🙏 💙

2022-12-30 07:27 UTC, bomyuniverse commented on ContactManager/ContactManager/Model/ContactManager.swift
> +    enum MenuStart: String, CustomStringConvertible {
메뉴를 열거형으로 가지고 있는 것이라 Start보다 List로 작성하는 게 더 명시적일 것 같습니다! 추천 감사합니다! 👍

2022-12-30 07:32 UTC, bomyuniverse commented on ContactManager/ContactManager/Model/ContactManager.swift
> +        let splitedUserInputValues = combinedUserInputValues.split(separator: "/").map{ String($0) }
고차함수를 처음 사용해 보면서 발생한 실수였습니다! 자세한 이유는 아래에 작성해 두었습니다! 감사합니다! 🙏 💙

2022-12-30 07:33 UTC, bomyuniverse commented on ContactManager/ContactManager/Storage/PrintMessage.swift
> +    static func viewContact(list: Set<ContactInformation>) {
printContact와 viewContact 사이에서 고민하다가 보여준다는 의미에서 view를 채택하였는데, 이름에 대해 Jason과 함께 논의 후 결정해보겠습니다! 조언 감사합니다! 👍

2022-12-30 07:34 UTC, bomyuniverse commented on ContactManager/ContactManager/Model/ContactManager.swift
> +        if receiveUserInputValues == "" {
초반에 해당 메서드의 return값을 설정하는 과정에서 발생했던 실수입니다! 해당 부분 정정하겠습니다! 감사합니다!! 👍 💙

2023-01-02 02:13 UTC, zdodev commented on ContactManager/ContactManager/Model/Checker.swift
> +        var phoneNumberValue: String = ""
현업에서도 팀 코드 컨벤션에 따라 달라질 수 있는 부분이라 생각합니다. 개인적으로 생략하는 스타일을 더 선호합니다!

2023-01-02 02:18 UTC, zdodev commented on ContactManager/ContactManager/Model/ContactManager.swift
> +        } while identifier == true
`identifier == true` 또는 `identifier == false` 와 같이 비교 대상이 `Bool` 인 경우 프로퍼티 자체가 이미 `true` or `false` 조건을 나타내고 있어서 비교 구문을 작성하지 않고 프로퍼티만 작성해도 좋지 않을까 싶었습니다!

2023-07-07 02:40 UTC, closed without merging