연락처관리 [STEP 2,3] Is, Sunny
tasty-code/ios-cantact-manager pull request #17
Opened 2022-12-30 06:11 UTC by SunnnySong

안녕하세요 vivi(@YebinKim)☺️ 벌써 2022년의 마지막날이 성큼 다가왔습니다! 저희는 12월에 새싹을 시작하느라 12월의 시간이 순삭이 되어버렸는데 vivi의 12월은 어땠을지 궁금해요. ㅎㅎ

먼저 저번 Step 1 PR 리뷰를 너무나 정성스럽게 적어주셔서 감사합니다! 리뷰를 보면서 모르는 것에 대해 알게 된 것 뿐만 아니라 개념적으로는 알고 있었지만 코드를 작성할 때 적용하지 못했던 개념까지 다시 한번 더 생각하게 되는 계기가 되었어요.😁  이번 코드에서 최대한 저번에 받은 리뷰가 다시 나오지 않도록 작성하려 노력했습니다!

리뷰로 배우는게 엄청 많아서 못 받으면 어쩌지 걱정했는데 시간이 촉박했던 저희를 위해 금요일까지 리뷰 기간을 연장해주셔서 감사해요💜
2023년 행복한 한 해 보내세요😊

# 큰그림🍪
## 객체 정리

| Type        | 이름                 | 역할                                                                                                                                                                                              | 비고                       |
| ----------- | -------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------- |
| enum        | StringLiteral        | 프로그램 내 상수 문자열들                                                                                                                                                                         | 나중에 .strings로 바꿔보자 |
| enum        | IOManager, PrintType | 프로그램 내 입력, 출력 담당                                                                                                                                                                       |                            |
| enum        | IOError              | 프로그램 입출력 Error 정리                                                                                                                                                                        |                            |
| final class | ContactManager       | 사용자에게 받은 입력을 1차 검증함<br>- 주어진 메뉴만 입력했는지<br>- 연락처 정보 중 '/' 형식 지켰는지<br>- 검색하려는 이름 형식 지켰는지<br>Phonebook, userInfo와 소통해 연락처 정보를 관리, 검색 |                            |
| final class | Phonebook            | 연락처를 관리하는 전화번호부<br>CM의 요청에 따라 연락처 추가, 설명 반환                                                                                                                           |                            |
| struct      | UserInfo             | 유저 정보를 담은 구조체<br>init시 입력 받은 연락처 정보의 이름, 나이, 연락처를 검증함                                                                                                             |                            |

## 순서도

### 전체

![전체](https://user-images.githubusercontent.com/107124308/209934044-63ca5042-a1e3-47b1-bfad-c9039f5bc942.png)

### 연락처 추가

![연락처_추가](https://user-images.githubusercontent.com/107124308/210035292-4bb6031c-3cd4-4103-9029-81fe8184e172.jpeg)

### 연락처 목록 조회

![연락처_목록_조회](https://user-images.githubusercontent.com/107124308/210035277-99322972-308f-46f8-a926-5e335748cdf8.jpeg)

### 연락처 검색

![연락처_검색](https://user-images.githubusercontent.com/107124308/210035299-3280cf8e-d062-4e66-8539-351441c11f13.jpeg)

# 구현 요구 사항 및 작업 목록

## Step 2 - 사용자 메뉴 표기

### 구현 요구 사항

- 사용자에게 동작을 선택할 메뉴를 표기합니다.
- 1, 2, 3, x 외의 입력을 받으면 잘못된 입력을 알리고 다시 메뉴를 출력합니다.
- 연락처 추가와 종료 기능만 우선 구현합니다.
- 연락처 목록보기와 연락처 검색 기능은 다음 스텝에서 구현합니다.

### 작업 목록

- [x] Menu 안내를 위한 StringLiteral 추가
- [x] Menu 입력 검증
  - [x] enum Menu, rawValue로 잘못된 입력이 들어왔을 때 nil 반환
  - [x] 잘못된 입력이 들어오면 콘솔에 안내한 후 run 함수 다시 실행
- [x] Phonebook class 생성
  - [x] 연락처는 key가 이름이고 value가 UserInfo의 ~~Array~~Set인 contacts에, 같은 이름인 UserInfo를 ~~append~~insert하는 방식으로 저장
- [x] 연락처 추가 기능 구현
  - [x] 중복인 연락처를 추가하지 않기 위해 Set 구현 및 안내 문구 추가
- [x] Improve 접근 제어 수정, 가독성 향상
  - 접근 제어
    - [x] ContactManager의 inputPattern, phonebook에 private
    - [x] PB contacs에 private
  - [x] Phonebook class에 final 붙임
  - 가독성 향상
    - [x] IOManager.sendOutput 개행
    - [x] CM-addContact 내 splitedInput map 함수에서 개행
- [x] 프로그램 종료 구현

## Step 3 - 목록 / 검색 기능 구현

- 목록은 이름 순으로 출력합니다.
- 검색 결과의 출력 순서는 입력받았던 순서와 무관합니다.

### 작업 목록

**목록 조회**

- [x] key sort 구현
- [x] sort된 키를 바탕으로 user info 프린트 string 구현
- [x] Phonebook의 description property: String?
  - phonebook에 연락처가 등록되지 않은 경우 nil을 반환
    **검색**
- [x] 사용자 입력 받기
- [x] 이름 검증
  - 기존의 UserInfoParameters를 활용
- [x] phonebook에 존재하는지 확인 후 결과 반환
  - [x] 찾는 이름이 contacts의 key라면, value를 description로 만든 후 반환
  - [x] 없으면 nil을 반환

### 공통

- [x] 필요한 StringLiteral 추가
- [x] 리팩토링

### 스텝/프로젝트 수행 중 핵심 경험

- Swift API Design Guide에 따른 이름짓기
- 소스코드에 불필요한 코드 및 코멘트 남기지 않기
- 메서드의 기능단위 분리
- 타입의 캡슐화/은닉화
- 상황에 알맞은 상수/변수의 올바른 선택
- Git의 커밋단위 고민하기
- Git 커밋 로그 형식 고민하기

## 프로그램 작동 예시
1. 메뉴
    - 올바른 메뉴 선택
        ![올바른메뉴선택](https://user-images.githubusercontent.com/107124308/210037642-425059a7-6090-48fd-8fa9-a17c7b283cf7.png)
    - 바르지 못한 메뉴 선택
        ![바르지못한메뉴](https://user-images.githubusercontent.com/107124308/210037643-af33b30b-27aa-4c68-a645-23bb2b2a969f.png)
    - 종료       
         ![종료](https://user-images.githubusercontent.com/107124308/210037645-82cd0dd6-bb08-4c2c-a624-e1c883fcd302.png)
2. 연락처 추가
   - Step 1에서 보여드린 연락처 추가와 동일한 코드이기 때문에 연락처 검증 test case 별 동작 사진은 따로 첨부하지 않겠습니다.
   - 중복 되지 않는 연락처 추가
   ![_/_](https://user-images.githubusercontent.com/107124308/210038101-3bce8b3f-0bc8-43da-98e3-4ba76d70d591.png)
   ![/](https://user-images.githubusercontent.com/107124308/210038107-d8eeca47-792f-4281-baad-52f13b12195f.png)
   - 중복된 연락처 추가
   ![중복연락처](https://user-images.githubusercontent.com/107124308/210038375-a0542af1-1d91-408c-9f31-bec226bcf437.png)
3. 연락처 전체 조회
![조회](https://user-images.githubusercontent.com/107124308/210038896-e735b220-1659-407a-89e4-8b899b4a281e.png)
4. 연락처 검색
![검색](https://user-images.githubusercontent.com/107124308/210038884-16f78ccc-781b-48e8-8923-3c9aacd91903.png)
# 고민과 해결

## 1. 연락처 표현 - UserInfo 표현 방식이 1+1개 ⁉️

![연락처_표현_예시](https://user-images.githubusercontent.com/107124308/209938757-b22b8beb-158f-4962-a8de-e0194ebc1bab.png)

```swift
// 표현 1
"\(self.age)세 \(self.name)(\(self.phone))"
// 표현 2
"\(self.name) / \(self.age) / \(self.phone)"
```

**문제 상황**

- Step1, 2에서는 1번 표현만 있었기에, UserInfo에 CustomStringConvertible 프로토콜을 채택한 후 1번을 default description으로 적용 및 구현했어요.
- 그런데, Step3에서 표현이 1개 추가되어 어떤 표현을 default description으로 해야 하는지, 더 나아가 하나의 default description으로 이를 해결할 수 있을지 고민했어요.

- 우선 프로젝트 특성 상 기본 표현은 검색 시 출력되는 **2번 표현**이라고 생각했어요.

**expected**

- 가능하다면 하나의 description property로
  - UserInfo의 property를 최대한 적게 하기 위해,
  - property 연산 시 switch case 문으로 분기해 다른 표현을 반환하면 좋을 것 같다고 생각했어요.
- 그렇지만, 위의 switch 문에서 사용되는 변수가 UserInfo 외부에 있는 편을 선호했어요.
  - 해당 description이 어디에서 필요로하는가에 따라 다른 표현이 출력되기 떄문에
  - 이는 UserInfo의 내부 상태로 있을 필요가 없다고 생각했기 때문입니다.

### 해결하기 위해...

```swift
enum PrintType {
    case a, b
}

//public var currentPrintType: PrintType
struct Person : CustomStringConvertible{
    static var currentPrintType: PrintType = .a
//    let printType: PrintType
    let name: String
    let nickname: String

    var description: String {
        switch Self.currentPrintType {
        case .a:
            return name
        case .b:
            return nickname
        }
    }
}

//Person.currentPrintType = .a
let 길동 = Person(name: "홍길동", nickname:"Hong")
print(길동) // 홍길동
Person.currentPrintType = .b
let 영희 = Person(name: "김영희", nickname: "Hee")
print(영희) // Hee
```

1. Person 안에 printType stored property를 만들면 switch-case description 가능 ⭕️
   ```swift
   struct Person : CustomStringConvertible{
     let name, nickName: String
     let printType: PrintType
   }
   ```
2. Person의 Type Property 생성 후 print 전에 변경하면 switch-case description 가능 ⭕️
3. 외부 변수 currentTypeProperty를 만들고 description의 switch-case 문에서 이를 이용 ❌<br>

❓ 이게 실제로 안되는건지, 저희가 잘못한건지 궁금해요!

### 선택 및 구현

하나의 description에서 처리하는 것은 포기하고 property를 하나 더 만들기로 했어요🥹

```swift
extension UserInfo: CustomStringConvertible {
    var description: String {
        return "\(self.name) / \(self.age) / \(self.phone)"
    }

    var addedDescription: String {
        return "\(self.age)세 \(self.name)(\(self.phone))"
    }
}
```

## 2. 연락처 검색 - 사용자가 이름 입력할 때 " "를 허용할 것인가?

### 가능한 해결

1. 검색 시에도 " " 허용하고 검색할 이름을 입력받은 후 공백을 제거합니다.
   - **이유** 연락처 추가할 때 " " 허용하고 이를 없앴기 때문에, 검색 역시 이를 일관적으로 적용하자!
2. 검색시에는 " "를 허용하지 말자
   - **이유** 'a bc'와 'ab c'를 검색했을 때 동일한 결과가 나오는 것은 이상하다! [...]

2023-01-01 13:29 UTC, YebinKim requested changes
써니, 이즈 안녕하세요~
Step2와 Step3를 함께 진행하느라 고생 많으셨습니다!!
이번에도 엄청나게 꼼꼼한 README를 보면서..!! 👀 써니와 이즈가 얼마나 많은 고민을 하셨는지 알 수 있었어요 ㅎㅎ

우선 질문주셨던 부분 및 고민하셨던 부분들에 대해 제 의견부터 한 번 남겨볼게요!!

---

### 1. 연락처 표현 - UserInfo 표현 방식이 1+1개 ⁉️
#### -> `외부 변수 currentTypeProperty를 만들고 description의 switch-case 문에서 이를 이용` 이 불가능한 것인지?

우선, 제가 질문을 제대로 이해한 게 맞다면 외부 변수를 enum의 연산 프로퍼티에서 분기 구문의 상태문으로서 활용하는 것은 가능해요! 실제로 제가 아래와 같이 코드를 작성해봤는데 잘 동작했습니다 (Playground 에서 실행했어요)

```swift
enum PrintType {
    case a, b
}

var printType: PrintType = .a

//public var currentPrintType: PrintType
struct Person : CustomStringConvertible{
    let name: String
    let nickname: String

    var description: String {
        switch printType {
        case .a:
            return name
        case .b:
            return nickname
        }
    }
}
```

다만, `Person` 객체가 `currentPrintType` 상태에 의존하는 방식으로 `description`을 출력하게 되면 `Person` 객체는 출력 모양만을 바꾸기 위해 상태를 변경해주는 과정이 한 번 더 필요하고 `currentPrintType `과 `description` 은 문법상 강제로 연결(의존)되어 있지 않지만 논리 구조 상으로는 의존되어 있기 때문에 프로그래머가 실수하기 쉬울 거 같아요.

그래서 가능하면 프로퍼티 상태에 의존하지 않는 형태로 구현할 수 있도록 연산 프로퍼티보다는 메서드 등을 활용해보는 것도 생각해볼 수 있을 거 같습니다 ☺️ (상태에 의존하지 않는 것이 좋다는 것은 앞으로 객체 지향 패러다임 또는 함수형 패러다임을 배우시면서 또 익히게 되실 거 같아요!)

### 2. 연락처 검색 - 사용자가 이름 입력할 때 “ “를 허용할 것인가?

저는 이 부분은 프로그래머의 구현 상 편의보다도 기능의 요구사항이 중요하다고 생각해요! **사용자의 입장**에서 무엇이 필요할지도 고민해보면 좋을 거 같습니다 ㅎㅎ

### 3. 연락처 데이터 저장 방식 / 데이터 구조

제가 이해하고 있기로는 `Phonebook`이 struct가 된다면 reference count는 증가하지 않습니다. Heap에 저장되기 때문에 reference count 가 증가한다고 생각하신 걸까요?? 🤔
또한, `Phonebook`이 struct 일 때 reference count 를 확인하는 디버깅 화면을 첨부합니다!
<img width="852" alt="debug" src="https://user-images.githubusercontent.com/38066039/210172217-a15e8385-c642-43ea-ae81-66856322a737.png">

### 4. Dictionary를 선택한 이유

어떤 타입으로 저장하는 게 좋을지 고민하신 부분은 이해됐어요! 다만, **현재 요구사항에 따르면 이름이 중복되어 저장될 수 있기 때문에 이름을 key로 하는 Dictionary를 사용하게 되면 동작 상 오류**가 발생하게 될 것으로 예상돼요 🤔
실제로 이 부분과 관련해 오류가 발생하고 있기도 하구요.

그리고 평균 시간 복잡도는 반복문 for 를 돌리는 것을 기준으로 생각하신 걸까요?
어떤 방식으로 순회를 하는지(고차함수를 사용하진 않는지)에 따라 시간 복잡도는 달라질 수 있을 거 같아요.
**단순히 for 반복문을 사용한다고 했을 때, 검색과 조회의 시간 복잡도가 다른 이유 그리고 Array와 Set의 조회 시 시간 복잡도가 O(NlogN) 이라고 생각하신 이유가 궁금합니다 👀**

#### -> 연락처 중복 추가 방지를 위해**Set<UserInfo>**로 변경
또한, 위에서 말씀드린 것과 같이 `이름-나이-번호 가 모두 동일`한 연락처 뿐만 아니라 이름만 동일한 연락처도 Dictionary의 특성 때문에 추가가 되지 않는 오류가 있어요.

### 5. 연락처 호출 방식 2가지의 효율성

어떤 효율성을 원하는지에 따라 적절한 코드가 달라질 수 있기 때문에 제가 질문을 잘 이해했을지 모르겠어요 🤔
시간을 기준으로 생각해보자면 두 방법의 시간 차이가 크지 않고, **가독성**을 생각했을 때 위의 코드가 더 쉽게 읽힌다는 생각이 들었어요.
좋은 코드에 대한 기준은 사람마다, 팀마다, 상황에 따라 다르며 효율성만이 절대적인 척도가 아니라는 것을 함께 이해하고자 한 번 더 언급드립니다 😄

### 6. 연락처 호출 방식의 모델링

저는 이 부분이 모델링 또는 역할 보다는 구현 방식의 차이로 생각했어요!
기준이 무엇일지에 따라 더 적합한 구현 방법 또한 달라질 거 같아요~ 가독성을 기준으로는 위 코드가 더 좋아보인다는 개인적인 의견입니다!

### 7. 성능 테스트 방법

이번에 써니와 이즈가 작성하신 [메서드들](https://gist.github.com/vanism2091/8aa2b49baa6c5e99b7673f7d5fdb5f5f)과 같이 테스트 코드를 작성해볼 수도 있지만, 저는 XCTest와 Instrument 를 활용하는 것을 선호해요!
성능 뿐만 아니라 테스트 전반을 잘 수행하기 위해서 메서드가 하나의 역할만 수행하고 각 클래스/구조체가 단일의 역할을 가질 수 있도록 테스트가 수월한 모델을 만드는 게 하나의 팁이 될 수 있을 거 같습니다 ☺️

### 8. 무한루프를 반복문(while true)에 비해 재귀함수로 구현하는 것의 이점?

저는 재귀함수와 반복문 둘 중 하나가 절대적으로 더 좋은 방법이라고 생각하지 않지만, 써니와 이즈가 잘 분석해주신 내용 외에 재귀함수의 장점을 하나 더 꼽아보자면 함수형 프로그래밍 관점에서 재귀함수는 상태(state)가 아닌 연산 문맥(context)을 기반으로 실행할 수 있다는 점을 들어볼 수 있을 거 같아요! 이 관점에 대한 얘기는 추후 **함수형 프로그래밍, 순수 함수,  동시성 문제(경쟁 상태, 데드락 등)**에 대해 학습한 후 다시 한 번 들여다보길 추천드립니다!

### 9. 삼항 연산자의 가독성

저는 이와 같은 상황이라면 삼항 연산자를 선호합니다~ 왜냐하면 if 구문으로 인해 라인 수가 많아지는 게 더 가독성이 좋지 않다고 생각하기 때문이에요!

### 10. 파일 구조화
기준이 너무 많아서 한 마디로 정리하기가 어렵네요 😅
저라면 파일을 나눌 때 프로그램의 아키텍처와 관련된 기능의 코드를 하나로 모으는 것 그리고 협업 중 발생하는 conflict 를 줄일 수 있는 방법을 기준으로 고민할 거 같습니다!

### 11. 네이밍

라인별 리뷰 중 더 꼼꼼히 확인했습니다! 😄

---

긴 코멘트 읽어주셔서 고맙습니다! ☺️
현재 기능 동작 중 오류가 있어서 Request Changes로 요청드렸어요.
1. 맞는 메뉴를 입력했는데 오류로 나오는 경우
<img width="464" alt="1-1" src="https://user-images.githubusercontent.com/38066039/210172226-26a84ef9-f30a-4387-97d7-4246f21d6f9e.png">

2. 연락처 정보 입력 시 메뉴 오류로 나오는 경우
<img width="466" alt="2" src="https://user-images.githubusercontent.com/38066039/210172281-29c4326b-e9d7-4e87-8a06-c2ede31d1201.png">

3. 중복된 이름의 연락처가 저장되지 않는 경우
<img width="464" alt="3" src="https://user-images.githubusercontent.com/38066039/210172253-91f355e0-b148-4571-b7d6-9e831645a5e7.png">

4. 연락처 정보가 잘못되었는데 이름이 잘못 되었다고 나오는 경우
<img width="464" alt="4" src="https://user-images.githubusercontent.com/38066039/210172258-876b5790-e283-49c8-bdd0-b674e506572f.png">

또한, 프로젝트 수행 기간이 끝나 리뷰 코멘트를 확인해주신 이후 이 PR은 추가 수정 없이 Close 진행하도록 하겠습니다. 😥

이즈, 써니 2주간 고생 많으셨어요!! ☺️🙇

2023-01-01 13:29 UTC, YebinKim commented on ios-contact-manager/ios-contact-manager/ContactManager.swift
> +    enum Menu: String {
메뉴를 enum 으로 case화 시켰군요! 메뉴가 추가되었을 때도 확장시키기 쉬울 거 같아요 🤩

2023-01-01 13:29 UTC, YebinKim commented on ios-contact-manager/ios-contact-manager/ContactManager.swift
> +        let description = inserted ? StringLiteral.Contact.added( userInfo.addedDescription) : StringLiteral.Contact.exist
p5;

불필요한 띄어쓰기가 있는 것으로 보여요 👀
```suggestion
        let description = inserted ? StringLiteral.Contact.added(userInfo.addedDescription) : StringLiteral.Contact.exist
```

2023-01-01 13:29 UTC, YebinKim commented on ios-contact-manager/ios-contact-manager/ContactManager.swift
> +        let description = phonebook.description ?? StringLiteral.Contact.empty
p3;

`phonebook.description`의 디폴트 값을 `StringLiteral.Contact.empty`로 사용하고자 한다면, `phonebook.description`이 반드시 옵셔널타입이어야 할까요?

2023-01-01 13:29 UTC, YebinKim commented on ios-contact-manager/ios-contact-manager/Phonebook.swift
> +    func getContact(of name: String) -> String? {
p3;

이전 리뷰에서 전달드렸듯, swift는 가능하면 get 네이밍을 지양하며, 저는 이 메서드가 get 보다는 search 에 가까운 동작이라고 생각하는데 혹시 어떻게 생각하실까요?? 🤔

2023-01-01 13:29 UTC, YebinKim commented on ios-contact-manager/ios-contact-manager/StringLiteral.swift
> +    }
p2;

현재 `Contact` case가 하나도 없는 것으로 보이는데요 👀 enum 을 사용하고자 한 이유가 무엇일까요?
단순히 문자열을 저장하고자 한다면 `StringLiteral`을 사용할 수는 없었는지도 궁금합니다!

현재와 같이 case 없이 enum 을 사용하는 것은 타입을 적절하게 사용하고 있는 게 맞을지 의문이 들어 수정이 필요해보여요.

2023-01-01 13:29 UTC, YebinKim commented on ios-contact-manager/ios-contact-manager/Phonebook.swift
> +    private var contacts: [String:Set<UserInfo>]
p5;

사소하지만 Dictionary에서 콜론의 뒤는 띄어쓰기를 하나 추가해서 사용하는 것을 지향합니다! 😄
* [Swift.org Dictionaries](https://docs.swift.org/swift-book/LanguageGuide/CollectionTypes.html) 참고

2023-01-01 13:49 UTC, vanism2091 commented on ios-contact-manager/ios-contact-manager/ContactManager.swift
> +        let description = phonebook.description ?? StringLiteral.Contact.empty
```swift

final class Phonebook {
    // ..
    var description: String {
        guard false == contacts.isEmpty else {
            return StringLiteral.Contact.empty
        }
        let sortedContacts = contacts.sorted { $0.key < $1.key }
        let result = sortedContacts.reduce("") { partialResult, contact in
            partialResult + description(of: contact.value)
        }
        return result
    }
    // ..
}
```

이렇게 하면 굳이 optional이 아니어도 괜찮아요!
저는 데이터 모델(?)인 Phonebook은 StringLiteral을 보고 있지 않으면 좋을 것 같다는 혼자만의 생각때문에 이를 모두 ContactManager에서 처리하는 방식으로 했고, 그래서 Phonebook은 연락처가 없으면 description에 nil을 반환 후 CM에서 기본 값을 넣어주긴 했는데, 그럴 필요는 없을까요?

2023-01-01 13:51 UTC, vanism2091 commented on ios-contact-manager/ios-contact-manager/Phonebook.swift
> +    func getContact(of name: String) -> String? {
동의합니다!

2023-01-01 13:55 UTC, vanism2091 commented on ios-contact-manager/ios-contact-manager/StringLiteral.swift
> +    }
StringLiteral type을 struct가 아닌 enum으로 결정한 이유와 동일합니다. constants를 struct가 아니라 enum으로 정의한다면, 이 코드를 작성하지 않은 또 다른 팀원이 실수로 instance를 만들 경우를 방지할 수 있어요. StringLiteral안에 여러 문자열들이 산재해있어서, 이를 Menu와 Contact라는 도메인?별로 그룹화 하기 위해 다시 enum을 이용해 묶어주었습니다!

2023-01-01 13:57 UTC, vanism2091 commented on ios-contact-manager/ios-contact-manager/Phonebook.swift
> +    private var contacts: [String:Set<UserInfo>]
```swift
private var contacts: [String: Set<UserInfo>]
```
이런식이군요! 감사합니다😆

2023-01-01 13:58 UTC, vanism2091 commented on ios-contact-manager/ios-contact-manager/ContactManager.swift
> +        let description = inserted ? StringLiteral.Contact.added( userInfo.addedDescription) : StringLiteral.Contact.exist
vivi... 꼼꼼히 봐주셔서 고마워요🥹 감동... 수정할게요!

2023-01-01 14:50 UTC, vanism2091 commented
## 1. 연락처 표현

> 상태에 의존하지 않는 것이 좋다

앞으로 객체 지향, 함수형 패러다임을 익히며 븨븨의 문장을 계속해서 곱씹어볼게요🥰!

## 2. 연락처 검색 " " 허용?

허용하지 않는 편이 코드가 깔끔하다는 구현상 편의 보다, 기능의 요구사항과 **사용자의 입장**이 더 중요하다는 븨븨의 코멘트에 동의해요!

## 3. 연락처 데이터 저장 방식 / 데이터 구조

WWDC2016 [Performance in Swift](https://developer.apple.com/videos/play/wwdc2016/416/)의 Reference Counting의 Struct containing references(13:56~) 부분을 보고 이와 같이 이해했어요.
Phonebook 자체는 struct이므로 reference counting이 증가하지 않지만, contacts인 Dictionary가, 그리고 contacts의 key인 String, value인 Set이 Heap에 저장되는 references 라고 생각했고 따라서 Phonebook이 Struct containing references라고 생각했기 때문이예요. (물론 Phonebook이 프로그램 실행 중 copy되거나 다른 함수의 argument로 pass되는 경우는 없지만...) 위와 같이 Phonebook이 struct containing references라고 이해했는데, 이 이해가 틀린걸까요?

## 4. Dictionary를 선택한 이유

**이름 중복 저장 불가?**

```swift
/// 이름, 나이, 연락처가 유효한 입력이라면 UserInfo가 만들어지고
/// UserInfo가 만들어지면 Phonebook의 add 메소드로
/// contacts의 contact.name의 value인 Set에 insert 됩니다!
final class Phonebook {
    func add(contact: UserInfo) -> Bool {
        let (inserted, _) = contacts[contact.name, default: Set<UserInfo>()].insert(contact)
        return inserted
    }
}
```

구현 상 이름이 중복되어 입력되어도 Dictionary의 value인 set에 insert될텐데 이상하네요🤔.. (위의 구현이 제 예상과 다르게 동작하나요?) <br>
프로그램 작동 예시에서도 같은 이름을 입력한 동작이 있었고, 제가 다시 테스트했을 때 잘 입력되는 것을 확인했습니다!
![중복입력예시](https://user-images.githubusercontent.com/107124308/210173784-612cb3de-c9e7-4f0c-9b42-bdd5461a4fed.png)

**평균 시간 복잡도**

네 for로 돌리는 것을 기준으로 생각했습니다!

1. 검색과 조회의 시간 복잡도가 다른 이유
    - set의 경우, hash 값으로 검색했을 때 O(1)이 나온다고 생각했어요. 
    - 그런데 UserInfo를 set으로 만들 때 hash에 먹인(?) 값이 이름, 나이, 연락처이기에 
    - 이름만으로 검색하면 일일이 봐야 한다고 생각했고,
    - 따라서 <b>O(N)</b>일 것 같았어요!
2. Array와 Set 조회 시 시간복잡도가 O(NlogN)이라고 생각한 이유
   - 조회 시 구현 사항인 '이름을 기준으로 오름차순 정렬'때문에, 
   - <b>정렬의 시간 복잡도인 O(NlogN)</b>이라고 생각했어요.

## 5,6. 효율성과 모델링

> 좋은 코드에 대한 기준은 사람마다, 팀마다, 상황에 따라 다르며 효율성만이 절대적인 척도가 아니다

명심할게요!

## 7. 성능 테스트 방법

XCTest, Instrument 활용 방법을 공부해봐야겠군요! 감사해요😘

## 8. 재귀함수의 이점

상태가 아닌 연산 문맥을 기반으로.. 공부할게 엄청 많아서 신나요🥹 <br>
좋은 방향을 제시해줘서 고마워요!

## 10. 파일의 구조화
메모메모!
>- 프로그램의 아키텍처와 관련된 기능의 코드를 하나로 모으는 것
>- 협업 중 발생하는 conflict 를 줄일 수 있는 방법

## 기능 동작 중 오류

Xcode의 콘솔 프로그램을 IDE 내 콘솔에서 실행했을 때, 입력 시 **방향키를 누르거나 한글을 입력했다가 지우면 올바른 입력으로 처리되지 않는 경우**가 왕왕 있더라구요! 혹시 이와 같은 경우는 아니었는지 궁금해요🤔

1. 맞는 메뉴를 입력했는데 오류로 나오는 경우
   - ❓ 제가 다시 테스트했는데 이런 현상을 확인하지 못했어요🥲
2. 연락처 정보 입력 시 메뉴 오류로 나오는 경우
   - 프로그램의 오류가 아니라
   - 메뉴를 선택할 때 연락처를 입력한 경우 같아요!
3. 중복된 이름의 연락처가 저장되지 않는 경우
   - ❓ 제가 다시 테스트했는데 이런 현상을 확인하지 못했어요🥲 (위에 작동 스샷을 첨부했어요!)
4. 연락처 정보가 잘못되었는데 이름이 잘못되었다고 나오는 경우
    - ❓ 이건 처음에는 연락처가 잘못됐는데 이름이 잘못되었나고 나오는걸 확인했는데,
    - print문으로 나눠서 확인해보니 그 이후에는 반복되지 않았어요. 뭐죠..? 프로그래밍계의 불확정성의 원리?
    ![올바른 동작 스샷](https://user-images.githubusercontent.com/107124308/210174719-da2cb8c8-2703-4cca-8483-55cd43eed7b9.png)
    - 다시 테스트하니 퍄퍄로 입력 후(한글 입력) 이를 지우고 
    - 이를 vivi로 입력했을 때 위와 같은 동일한 오류가 발생함을 확인했어요!
    ![오류 재현](https://user-images.githubusercontent.com/107124308/210174736-a81318ac-578e-4d54-a593-7a66d7dc1617.png)

늦은 밤 + 1월 1일인데 정성스러운 리뷰 고마워요! 해피 뉴 이어,, 내일 화이팅입니다❗️❤️‍🔥

2023-01-01 15:01 UTC, YebinKim commented
이즈~ 늦은 시간임에도 빠른 확인 고마워요! 😄
저도 다시 확인해본 후 중복 저장 동작 및 말씀드렸던 버그 리포트에서 콘솔창에 한글 입력 또는 방향키 입력이 없을 때 정상 동작하는 것을 확인했습니다 (콘솔의 문제였군요..!!)

이번 스텝들에서의 핵심 경험은 아래와 같았는데요.

<img width="350" alt="step2" src="https://user-images.githubusercontent.com/38066039/210175175-3d1dc33a-a46d-4f4d-9459-deeee835e2e6.png">
<img width="350" alt="step3" src="https://user-images.githubusercontent.com/38066039/210175179-d6e793a3-5696-4ce7-b9a1-9d7c1d7368da.png">

이 경험들은 충분히 수행되었다고 생각해 머지를 진행할게요 ㅎㅎ

새해 복 많이 받으시구 다음 프로젝트 진행도 화이팅입니다!! 💪🔥

2023-01-01 15:01 UTC, YebinKim approved these changes

2023-01-01 15:01 UTC, merged

2023-01-02 06:54 UTC, SunnnySong commented on ios-contact-manager/ios-contact-manager/Phonebook.swift
> +    func getContact(of name: String) -> String? {
동의합니다!!22